# Log Merger Tool for Second Life Logs
# By Ramen Jedburgh aka Noodles (SL)
# 
# Input two log files generated by a Second Life viewer with
# timestamps and it will merge them into one log file based
# on Timestamp and output a file Combined_log.txt

fileA = raw_input("Enter the first log filename:")

fileB = raw_input("Enter the second log filename:")

with open(fileA) as f:
    logA = [line.rstrip() for line in f]
with open(fileB) as f:
    logB = [line.rstrip() for line in f]

combined = []

whereB = 0

for x in logA:
   if x[0:1] == "[":
      nextB = logB[whereB]
      dateA = x[x.find("["):x.find("]")+1]
      dateB = nextB[nextB.find("["):nextB.find("]")+1]
      if dateA == min(dateA,dateB):
         combined.append(x)
      else:
         combined.append(nextB)
         whereB+=1

filewrite = open("Combined_log.txt", "w")

for i in combined:
   filewrite.write(i+"\n")

filewrite.close

